### ISSUE TITLE
Issue with library name

### ISSUE THREAD

**Issue by cmaglie** [ArduinoMax/AD5241#2]
Hi @ArduinoMax

we have detected that you changed the name of the library in `library.properties` from
  `AD5241`
to
  `ArduMax AD5241 Driver`
is that right?
We are introducing a change in the library manager that forbids this kind of changes and ignore the releases with the name that differs from the name registered in the library index.

Is it ok for you to keep the new name `ArduMax AD5241 Driver`? The older releases with a different name will be ignored by the library manager. In absence of an answer from you we will proceed with this proposal next week.

See also: https://github.com/arduino/Arduino/issues/7127

```
JOB 652 - 2018/01/15 15:43:28 Scraping https://github.com/ArduinoMax/AD5241.git
JOB 652 - 2018/01/15 15:43:28 Checking out tag: v1.0.0
JOB 652 - 2018/01/15 15:43:28 Release AD5241:1.0.0 already loaded, skipping
JOB 652 - 2018/01/15 15:43:28 Checking out tag: v1.0.1
JOB 652 - 2018/01/15 15:43:28 Release ArduMax AD5241 Driver:1.0.1 has wrong library name, should be AD5241
JOB 652 - 2018/01/15 15:43:28 Checking out tag: v1.0.2
JOB 652 - 2018/01/15 15:43:28 Release ArduMax AD5241 Driver:1.0.2 has wrong library name, should be AD5241
```

**Comment by xcvista** [comment]
Go ahead and rename it.
